-- Reference data so a fresh install has Automakers and Brands to pick from instead of every
-- Collector typing in "Ferrari" or "Hot Wheels" themselves. Both tables are shared across
-- Collectors (not per-user) and their names are unique.
--
-- "on conflict (name) do nothing" keeps this safe on databases where someone already created a
-- row with one of these names (local dev data): the existing row, and any Models pointing at it,
-- are left alone.
--
-- Automakers include motorcycle makers and Formula 1 constructors, since both are common diecast
-- subjects. Country is where the marque comes from, not who owns it today (Bentley is
-- United Kingdom, not Germany); F1 constructors use the nationality they raced under (Red Bull
-- Racing is Austria, Jordan is Ireland). F1 teams named after a road-car marque (Ferrari, McLaren,
-- Lotus, ...) share that marque's row.
--
-- Brands are the names printed on the packaging (see CONTEXT.md), so Hot Wheels and Matchbox are
-- separate Brands even though Mattel makes both.

insert into automaker (name, country) values
    -- United States
    ('AMC', 'United States'),
    ('Auburn', 'United States'),
    ('Buell', 'United States'),
    ('Buick', 'United States'),
    ('Cadillac', 'United States'),
    ('Checker', 'United States'),
    ('Chevrolet', 'United States'),
    ('Chrysler', 'United States'),
    ('Cord', 'United States'),
    ('DeLorean', 'United States'),
    ('DeSoto', 'United States'),
    ('Dodge', 'United States'),
    ('Duesenberg', 'United States'),
    ('Fisker', 'United States'),
    ('Ford', 'United States'),
    ('Freightliner', 'United States'),
    ('GMC', 'United States'),
    ('Harley-Davidson', 'United States'),
    ('Hennessey', 'United States'),
    ('Hudson', 'United States'),
    ('Hummer', 'United States'),
    ('Indian', 'United States'),
    ('International Harvester', 'United States'),
    ('Jeep', 'United States'),
    ('Kenworth', 'United States'),
    ('Lincoln', 'United States'),
    ('Lucid', 'United States'),
    ('Mack', 'United States'),
    ('Mercury', 'United States'),
    ('Nash', 'United States'),
    ('Oldsmobile', 'United States'),
    ('Oshkosh', 'United States'),
    ('Packard', 'United States'),
    ('Panoz', 'United States'),
    ('Peterbilt', 'United States'),
    ('Plymouth', 'United States'),
    ('Pontiac', 'United States'),
    ('Ram', 'United States'),
    ('Rivian', 'United States'),
    ('Saleen', 'United States'),
    ('Shelby', 'United States'),
    ('SSC', 'United States'),
    ('Studebaker', 'United States'),
    ('Tesla', 'United States'),
    ('Tucker', 'United States'),
    ('Vector', 'United States'),
    ('Victory', 'United States'),
    ('Willys', 'United States'),
    ('Zero', 'United States'),
    -- Canada
    ('Can-Am', 'Canada'),
    -- Germany
    ('Alpina', 'Germany'),
    ('Audi', 'Germany'),
    ('BMW', 'Germany'),
    ('Borgward', 'Germany'),
    ('DKW', 'Germany'),
    ('Horch', 'Germany'),
    ('MAN', 'Germany'),
    ('Maybach', 'Germany'),
    ('Mercedes-Benz', 'Germany'),
    ('MZ', 'Germany'),
    ('NSU', 'Germany'),
    ('Opel', 'Germany'),
    ('Porsche', 'Germany'),
    ('RUF', 'Germany'),
    ('Smart', 'Germany'),
    ('Trabant', 'Germany'),
    ('Volkswagen', 'Germany'),
    ('Wartburg', 'Germany'),
    ('Wiesmann', 'Germany'),
    ('Zündapp', 'Germany'),
    -- Italy
    ('Abarth', 'Italy'),
    ('Alfa Romeo', 'Italy'),
    ('Aprilia', 'Italy'),
    ('Autobianchi', 'Italy'),
    ('Benelli', 'Italy'),
    ('Bimota', 'Italy'),
    ('Bizzarrini', 'Italy'),
    ('Cagiva', 'Italy'),
    ('Cisitalia', 'Italy'),
    ('Dallara', 'Italy'),
    ('De Tomaso', 'Italy'),
    ('Ducati', 'Italy'),
    ('Ferrari', 'Italy'),
    ('Fiat', 'Italy'),
    ('Gilera', 'Italy'),
    ('Innocenti', 'Italy'),
    ('Iso', 'Italy'),
    ('Iveco', 'Italy'),
    ('Lamborghini', 'Italy'),
    ('Lambretta', 'Italy'),
    ('Lancia', 'Italy'),
    ('Laverda', 'Italy'),
    ('Maserati', 'Italy'),
    ('Moto Guzzi', 'Italy'),
    ('Moto Morini', 'Italy'),
    ('MV Agusta', 'Italy'),
    ('Pagani', 'Italy'),
    ('Piaggio', 'Italy'),
    ('Pininfarina', 'Italy'),
    ('Vespa', 'Italy'),
    -- United Kingdom
    ('AC', 'United Kingdom'),
    ('AEC', 'United Kingdom'),
    ('Ariel', 'United Kingdom'),
    ('Aston Martin', 'United Kingdom'),
    ('Austin', 'United Kingdom'),
    ('Austin-Healey', 'United Kingdom'),
    ('Bentley', 'United Kingdom'),
    ('Bristol', 'United Kingdom'),
    ('Brough Superior', 'United Kingdom'),
    ('BSA', 'United Kingdom'),
    ('Caterham', 'United Kingdom'),
    ('Dennis', 'United Kingdom'),
    ('Ginetta', 'United Kingdom'),
    ('Hillman', 'United Kingdom'),
    ('Jaguar', 'United Kingdom'),
    ('Jensen', 'United Kingdom'),
    ('Land Rover', 'United Kingdom'),
    ('LEVC', 'United Kingdom'),
    ('Leyland', 'United Kingdom'),
    ('Lister', 'United Kingdom'),
    ('Lotus', 'United Kingdom'),
    ('Matchless', 'United Kingdom'),
    ('McLaren', 'United Kingdom'),
    ('MG', 'United Kingdom'),
    ('Mini', 'United Kingdom'),
    ('Morgan', 'United Kingdom'),
    ('Morris', 'United Kingdom'),
    ('Noble', 'United Kingdom'),
    ('Norton', 'United Kingdom'),
    ('Reliant', 'United Kingdom'),
    ('Rolls-Royce', 'United Kingdom'),
    ('Rover', 'United Kingdom'),
    ('Royal Enfield', 'United Kingdom'),
    ('Sunbeam', 'United Kingdom'),
    ('Triumph', 'United Kingdom'),
    ('TVR', 'United Kingdom'),
    ('Vauxhall', 'United Kingdom'),
    ('Vincent', 'United Kingdom'),
    -- France
    ('Alpine', 'France'),
    ('Bugatti', 'France'),
    ('Citroën', 'France'),
    ('De Dion-Bouton', 'France'),
    ('Delage', 'France'),
    ('Delahaye', 'France'),
    ('DS Automobiles', 'France'),
    ('Facel Vega', 'France'),
    ('Ligier', 'France'),
    ('Matra', 'France'),
    ('Panhard', 'France'),
    ('Peugeot', 'France'),
    ('Renault', 'France'),
    ('Simca', 'France'),
    ('Talbot', 'France'),
    -- Sweden
    ('Husqvarna', 'Sweden'),
    ('Koenigsegg', 'Sweden'),
    ('Polestar', 'Sweden'),
    ('Saab', 'Sweden'),
    ('Scania', 'Sweden'),
    ('Volvo', 'Sweden'),
    -- Netherlands
    ('DAF', 'Netherlands'),
    ('Donkervoort', 'Netherlands'),
    ('Spyker', 'Netherlands'),
    -- Czech Republic
    ('Jawa', 'Czech Republic'),
    ('Tatra', 'Czech Republic'),
    ('Škoda', 'Czech Republic'),
    -- Spain
    ('Bultaco', 'Spain'),
    ('Cupra', 'Spain'),
    ('Derbi', 'Spain'),
    ('Gas Gas', 'Spain'),
    ('Hispano-Suiza', 'Spain'),
    ('Montesa', 'Spain'),
    ('Pegaso', 'Spain'),
    ('SEAT', 'Spain'),
    -- Austria
    ('KTM', 'Austria'),
    ('Puch', 'Austria'),
    -- Monaco
    ('Venturi', 'Monaco'),
    -- Croatia
    ('Rimac', 'Croatia'),
    -- Denmark
    ('Zenvo', 'Denmark'),
    -- Romania
    ('Dacia', 'Romania'),
    -- Serbia
    ('Zastava', 'Serbia'),
    -- Russia
    ('GAZ', 'Russia'),
    ('KAMAZ', 'Russia'),
    ('Lada', 'Russia'),
    ('Moskvitch', 'Russia'),
    ('UAZ', 'Russia'),
    ('Ural', 'Russia'),
    ('ZIL', 'Russia'),
    -- Japan
    ('Acura', 'Japan'),
    ('Daihatsu', 'Japan'),
    ('Datsun', 'Japan'),
    ('Hino', 'Japan'),
    ('Honda', 'Japan'),
    ('Infiniti', 'Japan'),
    ('Isuzu', 'Japan'),
    ('Kawasaki', 'Japan'),
    ('Lexus', 'Japan'),
    ('Mazda', 'Japan'),
    ('Mitsubishi', 'Japan'),
    ('Mitsuoka', 'Japan'),
    ('Nissan', 'Japan'),
    ('Prince', 'Japan'),
    ('Scion', 'Japan'),
    ('Subaru', 'Japan'),
    ('Suzuki', 'Japan'),
    ('Toyota', 'Japan'),
    ('Yamaha', 'Japan'),
    -- South Korea
    ('Daewoo', 'South Korea'),
    ('Genesis', 'South Korea'),
    ('Hyundai', 'South Korea'),
    ('Kia', 'South Korea'),
    ('SsangYong', 'South Korea'),
    -- China
    ('BYD', 'China'),
    ('CFMoto', 'China'),
    ('Changan', 'China'),
    ('Chery', 'China'),
    ('Dongfeng', 'China'),
    ('GAC', 'China'),
    ('Geely', 'China'),
    ('Great Wall', 'China'),
    ('Haval', 'China'),
    ('Hongqi', 'China'),
    ('Li Auto', 'China'),
    ('Lynk & Co', 'China'),
    ('NIO', 'China'),
    ('SAIC', 'China'),
    ('Wuling', 'China'),
    ('Xiaomi', 'China'),
    ('XPeng', 'China'),
    ('Zeekr', 'China'),
    -- India
    ('Bajaj', 'India'),
    ('Hindustan Motors', 'India'),
    ('Mahindra', 'India'),
    ('Maruti Suzuki', 'India'),
    ('Tata', 'India'),
    -- Australia
    ('Holden', 'Australia'),
    -- Malaysia
    ('Perodua', 'Malaysia'),
    ('Proton', 'Malaysia'),
    -- Vietnam
    ('VinFast', 'Vietnam'),
    -- Formula 1 constructors, United Kingdom
    ('Arrows', 'United Kingdom'),
    ('BAR', 'United Kingdom'),
    ('Brabham', 'United Kingdom'),
    ('Brawn GP', 'United Kingdom'),
    ('BRM', 'United Kingdom'),
    ('Cooper', 'United Kingdom'),
    ('Hesketh', 'United Kingdom'),
    ('Lola', 'United Kingdom'),
    ('Manor', 'United Kingdom'),
    ('March', 'United Kingdom'),
    ('Racing Point', 'United Kingdom'),
    ('Stewart', 'United Kingdom'),
    ('Surtees', 'United Kingdom'),
    ('Toleman', 'United Kingdom'),
    ('Tyrrell', 'United Kingdom'),
    ('Vanwall', 'United Kingdom'),
    ('Williams', 'United Kingdom'),
    -- Formula 1 constructors, Austria
    ('Red Bull Racing', 'Austria'),
    -- Formula 1 constructors, Italy
    ('AlphaTauri', 'Italy'),
    ('Minardi', 'Italy'),
    ('Racing Bulls', 'Italy'),
    ('Toro Rosso', 'Italy'),
    -- Formula 1 constructors, Switzerland
    ('Sauber', 'Switzerland'),
    -- Formula 1 constructors, United States
    ('Eagle', 'United States'),
    ('Haas', 'United States'),
    ('Penske', 'United States'),
    -- Formula 1 constructors, France
    ('Larrousse', 'France'),
    ('Prost', 'France'),
    -- Formula 1 constructors, Ireland
    ('Jordan', 'Ireland'),
    -- Formula 1 constructors, India
    ('Force India', 'India'),
    -- Formula 1 constructors, Japan
    ('Super Aguri', 'Japan'),
    -- Formula 1 constructors, Spain
    ('HRT', 'Spain'),
    -- Formula 1 constructors, Russia
    ('Marussia', 'Russia'),
    -- Formula 1 constructors, Canada
    ('Wolf', 'Canada'),
    -- Formula 1 constructors, Germany
    ('Zakspeed', 'Germany')
on conflict (name) do nothing;

insert into brand (name) values
    ('Ace Models'),
    ('Acme'),
    ('Almost Real'),
    ('Aoshima'),
    ('Atlas Editions'),
    ('Auto World'),
    ('AUTOart'),
    ('BBR'),
    ('Bburago'),
    ('BoS Models'),
    ('Brekina'),
    ('Busch'),
    ('California Collectibles'),
    ('Cararama'),
    ('CMC'),
    ('Corgi'),
    ('Dinky Toys'),
    ('DNA Collectibles'),
    ('Ebbro'),
    ('Era Car'),
    ('Ertl'),
    ('Exoto'),
    ('Gama'),
    ('Greenlight'),
    ('GT Spirit'),
    ('Herpa'),
    ('Hi-Story'),
    ('Hobby Japan'),
    ('Hongwell'),
    ('Hot Wheels'),
    ('Ignition Model'),
    ('Inno64'),
    ('IXO'),
    ('Jada Toys'),
    ('Johnny Lightning'),
    ('Kaido House'),
    ('Kinsmart'),
    ('Kyosho'),
    ('LCD Models'),
    ('Lesney'),
    ('Lionel Racing'),
    ('Lledo'),
    ('Looksmart'),
    ('M2 Machines'),
    ('Maisto'),
    ('Majorette'),
    ('Make Up'),
    ('Matchbox'),
    ('Matrix Scale Models'),
    ('Mebetoys'),
    ('Mercury'),
    ('Micro Turbo'),
    ('Mini GT'),
    ('Minichamps'),
    ('Model Car Group'),
    ('Motormax'),
    ('MR Collection'),
    ('Märklin'),
    ('Neo Scale Models'),
    ('New Ray'),
    ('Norev'),
    ('Ottomobile'),
    ('Oxford Diecast'),
    ('Para64'),
    ('Paudi'),
    ('Playart'),
    ('Polistil'),
    ('Pop Race'),
    ('Racing Champions'),
    ('Revell'),
    ('Road Champs'),
    ('Schuco'),
    ('Siku'),
    ('Solido'),
    ('Spark'),
    ('Stance Hunters'),
    ('Sun Star'),
    ('Tarmac Works'),
    ('Tecnomodel'),
    ('Tekno'),
    ('Tiny'),
    ('Tomica'),
    ('Tomica Limited Vintage'),
    ('Tootsietoy'),
    ('Top Speed'),
    ('Triple9'),
    ('TrueScale Miniatures'),
    ('Universal Hobbies'),
    ('Welly'),
    ('Whitebox'),
    ('Wiking'),
    ('Yat Ming')
on conflict (name) do nothing;
